# Generated by Django 3.2.8 on 2021-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdiagnosis', '0002_auto_20211008_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergysymptom',
            name='QuestionName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='coldsymptom',
            name='QuestionName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='musclesymptom',
            name='QuestionName',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
